/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 20-jul.-2019 9:28:06 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS afiliado CASCADE
;

DROP TABLE IF EXISTS agenda CASCADE
;

DROP TABLE IF EXISTS categoria CASCADE
;

DROP TABLE IF EXISTS cita CASCADE
;

DROP TABLE IF EXISTS consultorio CASCADE
;

DROP TABLE IF EXISTS especialidad CASCADE
;

DROP TABLE IF EXISTS medico CASCADE
;

DROP TABLE IF EXISTS multa CASCADE
;

DROP TABLE IF EXISTS sede CASCADE
;

DROP TABLE IF EXISTS tipo_cita CASCADE
;

DROP TABLE IF EXISTS usuario CASCADE
;

/* Create Tables */

CREATE TABLE afiliado
(
	k_identificacion numeric(9) NOT NULL,	-- Valor numérico el cual ha de ser único para el reconocimiento de una persona, dicho numero es otorgado por la registradora nacional.
	parentezco varchar(20) NULL,
	k_identificacion_afiliado numeric(9) NULL,	-- Valor numérico el cual ha de ser único para el reconocimiento de los beneficiarios que posea un afiliado, dicho número es otorgado por la registradora nacional.
	i_estado varchar(10) NOT NULL,	-- Indica en que estado se encuentra el paciente en la EPS ya sea inactivo, activo y retirado.
	i_estado_multa varchar(10) NOT NULL,	--  
	k_id_categoria numeric(2) NOT NULL
)
;

CREATE TABLE agenda
(
	k_id_agenda numeric(9) NOT NULL,
	i_estado varchar(10) NOT NULL,
	fecha date NOT NULL,
	h_inicio time without time zone NOT NULL,
	h_fin time without time zone NOT NULL,
	k_identificacion numeric(9) NULL,
	k_id_tipo numeric(9) NULL
)
;

CREATE TABLE categoria
(
	k_id_categoria numeric(2) NOT NULL,	-- Identifica cada tipo categoria
	v_copago numeric(7,2) NOT NULL,	-- Valor a pagar en el momento de la cita 
	v_multa numeric(7,2) NOT NULL	-- Indica el valor a pagar en caso de incumplimento
)
;

CREATE TABLE cita
(
	f_cita date NOT NULL,
	k_id_cita numeric(9) NOT NULL,
	i_estado varchar(20) NOT NULL,
	prescripcion varchar(255) NULL,
	diagnostico varchar(255) NULL,
	k_id_agenda numeric(9) NOT NULL,
	k_identificacion numeric(9) NULL,
	k_id_multa numeric(9) NULL
)
;

CREATE TABLE consultorio
(
	k_id_consultirio integer NOT NULL,
	i_tipo varchar(50) NOT NULL,
	descrip_equipo varchar(255) NOT NULL,
	k_id_sede varchar(20) NOT NULL
)
;

CREATE TABLE especialidad
(
	k_codigo numeric(9) NOT NULL,
	n_nombre varchar(20) NOT NULL
)
;

CREATE TABLE medico
(
	i_tiene_agenda boolean NOT NULL,	-- Indica si un médico abrio una agenda para atender a los pacientes en el mes.l
	k_identificacion numeric(9) NOT NULL,
	franja varchar(30) NULL,
	k_codigo_especiali numeric(9) NULL,
	k_id_consultirio integer NULL
)
;

CREATE TABLE multa
(
	i_estado varchar(10) NOT NULL,
	v_multa numeric(7,3) NOT NULL,
	k_id_multa numeric(9) NOT NULL
)
;

CREATE TABLE sede
(
	k_id_sede varchar(20) NOT NULL
)
;

CREATE TABLE tipo_cita
(
	k_id_tipo numeric(9) NOT NULL,
	duracion integer NOT NULL
)
;

CREATE TABLE usuario
(
	k_identificacion numeric(9) NOT NULL,	-- Valor numérico el cual ha de ser único para el reconocimiento de una persona, dicho numero es otorgado por la registradora nacional.
	i_tipo_document varchar(20) NOT NULL,	-- Indica que tipo  es la identificación del usuario: Cedula de Ciudadania, Tarjeta de Identidad,  NIT
	contrasea varchar(30) NOT NULL,	-- Es la contraseña que le permite al usario ingresar al sistema.
	"eMail" varchar(30) NULL,	-- Correo electrónico de la persona al cual le llegaran las notificaciones de los procesos realizados en la EPS. 
	q_tel_fijo varchar(7) NULL,	-- Línea telefónica la cual se ubica en la residencia de la persona.
	q_tel_cel varchar(11) NOT NULL,	-- Línea telefónica la cual permite contactar a la persona en caso de no poder al teléfono fijo.
	i_sexo varchar(1) NOT NULL,	-- Indicador en forma de carácter que indica el género de la persona ya sea con una H (hombre), M (mujer).
	n_persona varchar(40) NOT NULL,	-- Cadena de caracteres la cual es una designación verbal la cual se le es asignada a una persona para distinguirlo de otros.
	f_nacimiento date NOT NULL	-- Indicador del tiempo conformada por el día, mes y año en el que nació la persona en cuestión.
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE afiliado ADD CONSTRAINT "PK_Afiliado"
	PRIMARY KEY (k_identificacion)
;

ALTER TABLE afiliado ADD CONSTRAINT i_estado CHECK (i_estado IN( 'Inactivo', 'Activo',  'Retirado'))
;

ALTER TABLE afiliado ADD CONSTRAINT i_estado_multa CHECK (i_estado_multa IN('Multado','Sin multa'))
;

CREATE INDEX "IXFK_Afiliado_Categoria" ON afiliado (k_id_categoria ASC)
;

ALTER TABLE agenda ADD CONSTRAINT "PK_Agenda"
	PRIMARY KEY (k_id_agenda)
;

CREATE INDEX "IXFK_Agenda_Medico" ON agenda (k_identificacion ASC)
;

CREATE INDEX "IXFK_Agenda_Tipo_cita" ON agenda (k_id_tipo ASC)
;

ALTER TABLE categoria ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY (k_id_categoria)
;

ALTER TABLE categoria ADD CONSTRAINT v_multa CHECK ((v_multa >0))
;

ALTER TABLE categoria ADD CONSTRAINT v_copago CHECK (v_copago>0)
;

ALTER TABLE cita ADD CONSTRAINT "PK_Cita"
	PRIMARY KEY (k_id_cita)
;

ALTER TABLE cita ADD CONSTRAINT i_estado CHECK (i_estado IN('Cancelada','Cumplida','Incumplida'))
;

CREATE INDEX "IXFK_Cita_Afiliado" ON cita (k_identificacion ASC)
;

CREATE INDEX "IXFK_Cita_Agendar" ON cita (k_id_agenda ASC)
;

CREATE INDEX "IXFK_Cita_Multa" ON cita (k_id_multa ASC)
;

ALTER TABLE consultorio ADD CONSTRAINT "PK_Consultorio"
	PRIMARY KEY (k_id_consultirio)
;

ALTER TABLE consultorio ADD CONSTRAINT i_tipo CHECK (i_tipo IN('Medicina general','Pediatría','Ofrtalmologia','Odontología'))
;

CREATE INDEX "IXFK_Consultorio_Sede" ON consultorio (k_id_sede ASC)
;

ALTER TABLE especialidad ADD CONSTRAINT "PK_Especialidad"
	PRIMARY KEY (k_codigo)
;

ALTER TABLE medico ADD CONSTRAINT "PK_Medico"
	PRIMARY KEY (k_identificacion)
;

ALTER TABLE medico ADD CONSTRAINT franja CHECK (franja IN('Mañana','Tarde'))
;

CREATE INDEX "IXFK_Medico_Consultorio" ON medico (k_id_consultirio ASC)
;

CREATE INDEX "IXFK_Medico_Especialidad" ON medico (k_codigo_especiali ASC)
;

CREATE INDEX "IXFK_Medico_Usuario" ON medico (k_identificacion ASC)
;

ALTER TABLE multa ADD CONSTRAINT "PK_Multa"
	PRIMARY KEY (k_id_multa)
;

ALTER TABLE multa ADD CONSTRAINT i_estado CHECK (i_estado IN('Pagado','Debe'))
;

ALTER TABLE sede ADD CONSTRAINT "PK_Sede"
	PRIMARY KEY (k_id_sede)
;

ALTER TABLE tipo_cita ADD CONSTRAINT "PK_Tipo_cita"
	PRIMARY KEY (k_id_tipo)
;

ALTER TABLE tipo_cita ADD CONSTRAINT duracion CHECK (duracion>0)
;

ALTER TABLE usuario ADD CONSTRAINT "PK_Usuario"
	PRIMARY KEY (k_identificacion)
;

ALTER TABLE usuario ADD CONSTRAINT i_tipo_document CHECK (i_tipo_document
IN('CC',
'TI', 'NIT')
)
;

ALTER TABLE usuario ADD CONSTRAINT i_sexo CHECK (i_sexo
IN('M','F'))
;

/* Create Foreign Key Constraints */

ALTER TABLE afiliado ADD CONSTRAINT "FK_Afiliado_Categoria"
	FOREIGN KEY (k_id_categoria) REFERENCES categoria (k_id_categoria) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE afiliado ADD CONSTRAINT "FK_Afiliado_Usuario"
	FOREIGN KEY (k_identificacion) REFERENCES usuario (k_identificacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE agenda ADD CONSTRAINT "FK_Agendar_Medico"
	FOREIGN KEY (k_identificacion) REFERENCES medico (k_identificacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE agenda ADD CONSTRAINT "FK_Agendar_Tipo_cita"
	FOREIGN KEY (k_id_tipo) REFERENCES tipo_cita (k_id_tipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cita ADD CONSTRAINT "FK_Cita_Agenda"
	FOREIGN KEY (k_id_agenda) REFERENCES agenda (k_id_agenda) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cita ADD CONSTRAINT "FK_Cita_Afiliado"
	FOREIGN KEY (k_identificacion) REFERENCES afiliado (k_identificacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cita ADD CONSTRAINT "FK_Cita_Multa"
	FOREIGN KEY (k_id_multa) REFERENCES multa (k_id_multa) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE consultorio ADD CONSTRAINT "FK_Consultorio_Sede"
	FOREIGN KEY (k_id_sede) REFERENCES sede (k_id_sede) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE medico ADD CONSTRAINT "FK_Medico_Consultorio"
	FOREIGN KEY (k_id_consultirio) REFERENCES consultorio (k_id_consultirio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE medico ADD CONSTRAINT "FK_Medico_Especialidad"
	FOREIGN KEY (k_codigo_especiali) REFERENCES especialidad (k_codigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE medico ADD CONSTRAINT "FK_Medico_Usuario"
	FOREIGN KEY (k_identificacion) REFERENCES usuario (k_identificacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE afiliado
	IS 'Tabla que contiene los datos de aquellas personas que han de pedir la cita médica para que la ESP pueda asignarles
un médico que se trate su problema médico. '
;

COMMENT ON COLUMN afiliado.k_identificacion
	IS 'Valor numérico el cual ha de ser único para el reconocimiento de
una persona, dicho numero es otorgado por la registradora nacional.'
;

COMMENT ON COLUMN afiliado.k_identificacion_afiliado
	IS 'Valor numérico el cual ha de ser único para el reconocimiento de los beneficiarios que posea un afiliado, dicho número es otorgado por la
registradora nacional.'
;

COMMENT ON COLUMN afiliado.i_estado
	IS 'Indica en que estado se encuentra el paciente en la EPS ya sea inactivo, activo y retirado.'
;

COMMENT ON COLUMN afiliado.i_estado_multa
	IS ' '
;

COMMENT ON TABLE categoria
	IS 'Indica las propiedades de cada categoria  a la que pertenecen los usuarios.'
;

COMMENT ON COLUMN categoria.k_id_categoria
	IS 'Identifica cada tipo categoria'
;

COMMENT ON COLUMN categoria.v_copago
	IS 'Valor a pagar en el momento de la cita '
;

COMMENT ON COLUMN categoria.v_multa
	IS 'Indica el valor a pagar en caso de incumplimento'
;

COMMENT ON TABLE medico
	IS 'Un médico es un profesional que practica la medicina, este intenta de mantener y recuperar la salud de un
paciente mediante el estudio, el diagnóstico y el tratamiento de la enfermedad o lesión de este.'
;

COMMENT ON COLUMN medico.i_tiene_agenda
	IS 'Indica si un médico abrio una agenda para atender a los pacientes en el mes.l'
;

COMMENT ON TABLE usuario
	IS 'Posee todas aquellas características de vital importancia que permiten el registro, identificación y clasificación
teniendo en cuenta sus diversas cualidades de aquellos que hagan parte de la EPS ya sean pacientes o médicos.'
;

COMMENT ON COLUMN usuario.k_identificacion
	IS 'Valor numérico el cual ha de ser
único para el reconocimiento de una
persona, dicho numero es otorgado
por la registradora nacional.'
;

COMMENT ON COLUMN usuario.i_tipo_document
	IS 'Indica que tipo  es la identificación del usuario:
Cedula de Ciudadania,
Tarjeta de Identidad, 
NIT'
;

COMMENT ON COLUMN usuario.contrasea
	IS 'Es la contraseña que le permite al usario ingresar al sistema.'
;

COMMENT ON COLUMN usuario."eMail"
	IS 'Correo electrónico de la persona al cual le llegaran las notificaciones de los procesos realizados en la EPS. '
;

COMMENT ON COLUMN usuario.q_tel_fijo
	IS 'Línea telefónica la cual se ubica en
la residencia de la persona.'
;

COMMENT ON COLUMN usuario.q_tel_cel
	IS 'Línea telefónica la cual permite contactar a la persona en caso de no poder al teléfono fijo.'
;

COMMENT ON COLUMN usuario.i_sexo
	IS 'Indicador en forma de carácter que
indica el género de la persona ya sea
con una H (hombre), M (mujer).'
;

COMMENT ON COLUMN usuario.n_persona
	IS 'Cadena de caracteres la cual es una
designación verbal la cual se le es
asignada a una persona para
distinguirlo de otros.'
;

COMMENT ON COLUMN usuario.f_nacimiento
	IS 'Indicador del tiempo conformada
por el día, mes y año en el que nació
la persona en cuestión.'
;
